# information
# --------------------------
name: "SSen's Lab"
description: "SSen의 연구실 입니다."
url: "http://labs.ssen.name"


# document parser
# --------------------------
markdown: redcarpet
highlighter: pygments

#pygments: true
#kramdown:
#  input: GFM

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data"]
  # "superscript",

sass:
  sass_dir: assets
  # style: :compressed
